version: '3'
services:
  metric:
    tty: true
    stdin_open: true
    build: ./metric
    ports:
    - "88:3000"
    volumes:
    - "/dev:/dev"
    - "/dev/disk/:/dev/disk:ro"
    - "/var/run:/var/run:ro"
    - "/sys:/sys:ro"
    - "./metric:/app"
    depends_on:
    - mongodb
    networks: 
    - samplenet
  socketio:
    build: ./socketio
    ports:
    - "3000:3000"
    volumes:
    - "./socketio:/usr/src/app"
    depends_on:
    - mongodb
    networks: 
    - samplenet
 
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      samplenet:
        aliases:
          - "sampledb"
networks:
  samplenet:
    driver: bridge