version: '3'
services:
  web:
    build: ./monitor
    ports:
    - "88:3000"
    volumes:
    - "/dev:/dev"
    - "/var/run:/var/run:ro"
    - "/sys:/sys:ro"
    - "./monitor:/usr/src/app"
    depends_on:
    - mongodb
    networks: 
    - samplenet
  socketio:
    build: ./socketio
    ports:
    - "3000:3000"
    volumes:
    - "./socketio:/usr/src/app"
    depends_on:
    - mongodb
    networks: 
    - samplenet
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - './api:/app'
    environment:
      - MONGO_URI=mongodb://sampledb/sample
    depends_on: 
      - mongodb
    networks: 
      - samplenet
  nginx:
    restart: always
    image: nginx:1.13.3
    ports:
      - "8066:80"
    depends_on:
      - api
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks: 
      - samplenet
  
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      samplenet:
        aliases:
          - "sampledb"
networks:
  samplenet:
    driver: bridge